# **PART II: RAG SYSTEM**

**Group Members:**
- Casucci Leonardo (Student ID: 2196383)
- Frigo Gianmaria (Student ID: 2196376)

**Master Program:** Computer Engineering

---

## Project Motivation

This notebook implements a complete Retrieval-Augmented Generation (RAG) system over the Jeffrey Epstein court documents and disclosures dataset.

We chose this dataset for several key methodological reasons:
- **Unstructured and heterogeneous data:** The collection consists of raw emails, scanned court deposition transcripts, handwritten notes, and PDF filings. Unlike synthetic academic benchmarks, it presents real-world data issues including OCR errors, multi-column document layouts, missing metadata, and irregular timestamps.
- **Strict factual grounding:** Answering queries on legal disclosures requires high precision and verifiable source citations. Hallucinations or misattributions are particularly problematic in legal contexts, making this a strong testbed for source-aware chunking and explicit citation constraints.
- **Evaluation of hybrid retrieval:** The documents contain a mix of specific entity names, case numbers, dates, and broader conceptual discussions. This allows us to directly evaluate whether a hybrid retrieval strategy—combining dense semantic vectors with sparse BM25/TF-IDF keyword search, cross-encoder reranking, and adjacent chunk expansion—outperforms standard dense-only retrieval.

---

## Libraries Used and Rationale

The reusable pipeline code is organized across dedicated modules. Below is a breakdown of the primary libraries used and why each was selected:

- **Data Processing and Document Setup:**
  - `pandas`: Used for tabular data manipulation, metadata normalization, email deduplication, document schema consolidation, and generating structured evaluation summary tables.
  - `datasets` (Hugging Face): Used to load and cache the raw email dataset locally.
  - `paddleocr` / `PPStructureV3`: Used for layout-aware OCR on scanned PDF pages via PyTorch/Transformers. Selected because it preserves multi-column reading order and operates entirely locally without requiring external cloud OCR services.

- **Retrieval and Embeddings:**
  - `transformers` & `sentence-transformers`: Used to load `BAAI/bge-base-en-v1.5` for tokenization and computing 768-dimensional dense vector embeddings.
  - `scikit-learn` (`TfidfVectorizer`): Used for sparse lexical retrieval. Selected to complement dense vector search by providing exact keyword matching for specific proper names, dates, and legal terminology.
  - `faiss`: Used to build the L2 vector index for fast similarity search over chunk embeddings.
  - `ms-marco-MiniLM-L6-v2` (`cross-encoder`): Used as a reranker to compute joint query-passage cross-attention scores and select the top candidate passages before context assembly.

- **Generation and Evaluation:**
  - `llama-cpp-python`: Used to load GGUF quantized models (`gemma-4-E4B-it-heretic-GGUF`) with local GPU offloading for deterministic, private, and offline generation.
  - `google-genai` / `OpenRouter API` Used as provider-neutral API bindings to generate synthetic ground-truth test cases (`micro_test_set.json`) and run automated LLM-as-a-judge evaluation of accuracy, faithfulness, and citation metrics.

---

## Repository Structure

- `documents.py`: Email normalization, PDF OCR, schema mapping, and token-aware document chunking.
- `rag.py`: Dense and hybrid index construction, candidate reranking, prompt assembly, and local LLM generation.
- `evaluation.py`: Automated ground-truth test set generation and retrieval/answer evaluation metrics.
- `PART2.ipynb`: Complete experimental workflow demonstrating data ingestion, chunking, retrieval comparison, generation, and evaluation.

## Environment setup

Detects whether the notebook is running in Google Colab or locally. On Colab, it clones the project repository, sets the working directory, and installs dependencies including hardware-accelerated `llama-cpp-python`. Locally, it verifies that the working directory contains all required project modules (`documents.py`, `rag.py`, `evaluation.py`, `requirements.txt`).

In [1]:
import os
import sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    REPO = Path("/content/epstein-rag")

    if not REPO.exists():
        !git clone https://github.com/yammooo/epstein-rag.git /content/epstein-rag

    os.chdir(REPO)

    !pip install -q -r requirements.txt
    !pip install -q --upgrade llama-cpp-python \
        --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124

else:
    REPO = Path.cwd()

    required_files = [
        "documents.py",
        "rag.py",
        "evaluation.py",
        "requirements.txt",
    ]

    missing = [name for name in required_files if not (REPO / name).exists()]

    if missing:
        raise RuntimeError(
            "Run this notebook from the epstein-rag repository root. "
            f"Missing: {missing}"
        )

print(f"Environment: {'Google Colab' if IN_COLAB else 'local'}")
print(f"Working directory: {Path.cwd()}")

Environment: local
Working directory: /mnt/c/Users/gianm/Development/NLP

## Configuration & hyperparameters

Sets global configuration parameters, artifact cache file paths in `artifacts/`, embedding and reranker model identifiers (`BAAI/bge-base-en-v1.5`, `cross-encoder/ms-marco-MiniLM-L6-v2`), chunking and retrieval hyperparameters (dense/TF-IDF candidate counts, rerank anchors, neighbor window, maximum context chunks), evaluation provider settings (`openrouter`/`gemini`), and cache recomputation control flags.

In [2]:
from pathlib import Path

CACHE_DIR = Path("artifacts")
CACHE_DIR.mkdir(parents=True, exist_ok=True)

RAW_EMAILS_PATH = CACHE_DIR / "raw_dataset.parquet"
OCR_PAGES_PATH = CACHE_DIR / "ocr_pages.parquet"
CHUNKS_PATH = CACHE_DIR / "chunks_df.parquet"
EMBEDDINGS_PATH = CACHE_DIR / "embeddings.npy"
TEST_SET_PATH = CACHE_DIR / "micro_test_set.json"
DENSE_EVALUATION_PATH = CACHE_DIR / "evaluation_results.json"
HYBRID_EVALUATION_PATH = CACHE_DIR / "evaluation_results_hybrid.json"
PDF_DIR = CACHE_DIR / "epstein_files_pdfs"

EMBEDDING_MODEL_ID = "BAAI/bge-base-en-v1.5"
RERANKER_MODEL_ID = "cross-encoder/ms-marco-MiniLM-L6-v2"
MAX_CHUNK_TOKENS = 512
DENSE_CANDIDATES = 20
TFIDF_CANDIDATES = 20
RERANKED_ANCHORS = 5
NEIGHBORS = 1
MAX_CONTEXT_CHUNKS = 10
EVALUATION_PROVIDER = "openrouter"  # "gemini" or "openrouter"
EVALUATION_MODEL = "deepseek/deepseek-chat"
EVALUATION_REQUEST_DELAY = 0
MICRO_TEST_SET_SIZE = 16  # 8 PDF OCR pages and 8 emails

FORCE_LOAD_EMAILS = False
FORCE_RECOMPUTE_OCR = False
FORCE_RECOMPUTE_CHUNKS = False
FORCE_RECOMPUTE_EMBEDDINGS = False
FORCE_RECOMPUTE_TEST_SET = False
FORCE_RECOMPUTE_EVALUATION = False

# **LIBRARIES AND SYSTEM INITIALIZATION**

- **Data and documents:** `pandas`, `datasets` (Hugging Face), and `paddleocr` / `PPStructureV3`.
- **Retrieval:** `transformers`, `sentence-transformers`, `scikit-learn` (TF-IDF), and `faiss`.
- **Generation:** `llama-cpp-python` with GGUF Gemma model.
- **Evaluation:** `google-genai` / OpenRouter API bindings.

PPStructureV3 reads PDF files directly through Transformers/PyTorch, using GPU acceleration when available.

The code block below imports required libraries, defines an environment-agnostic secrets helper (`get_secret`) for Google Colab `userdata`, `.env`, environment variables, or interactive input fallback, and inspects PyTorch CUDA and `llama.cpp` GPU offload capabilities.

In [3]:
import gc
import os
from getpass import getpass

import llama_cpp
import pandas as pd
import torch
from transformers import AutoTokenizer

from documents import (
    add_email_fields,
    combine_documents,
    deduplicate_emails,
    duplicate_email_groups,
    email_dedup_key,
    emails_to_documents,
    load_email_dataset,
    load_or_build_chunks,
    load_or_ocr_pdfs,
    normalize_email_fields,
)
from evaluation import evaluate_answers, evaluate_retrieval, generate_ground_truth, make_text_generator
from rag import (
    build_index,
    build_prompt,
    build_tfidf_index,
    generate_answer,
    load_embedding_model,
    load_llm,
    load_or_compute_embeddings,
    load_reranker,
    retrieve_dense,
    retrieve_hybrid,
)


def get_secret(name, prompt):
    try:
        from google.colab import userdata
        value = userdata.get(name)
    except Exception:
        value = None
        try:
            from dotenv import load_dotenv
            load_dotenv()
        except ImportError:
            pass
    return value or os.getenv(name) or getpass(prompt).strip()


device = "cuda" if torch.cuda.is_available() else "cpu"
llama_cpp_gpu = bool(llama_cpp.llama_supports_gpu_offload())
print(f"Embedding device: {device}")
print(f"llama.cpp GPU offload available: {llama_cpp_gpu}")

ggml_cuda_init: found 1 CUDA devices (Total VRAM: 8191 MiB):
  Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5, VMM: yes, VRAM: 8191 MiB

Embedding device: cuda
llama.cpp GPU offload available: True

# **DATASET**

## Load raw emails

The original Hugging Face dataset is cached locally. PDF pages are handled in a
separate source-specific stage later; they are not treated as fake emails.

In [4]:
raw_emails = load_email_dataset(
    RAW_EMAILS_PATH,
    force=FORCE_LOAD_EMAILS,
)
raw_emails.head()

,doc_id,subject,preview,from_name,from_email,to,date,body
0,4accfb5f3ed84656e9762740081a4579,cody rudland: You are dead,- Lol good riddance,cody rudland,[redacted],<jeeproject@yahoo.com>,"Aug 13, 2019 6:48 AM",Lol good riddance
1,97d4a52d1df3948368770068262d2aab,Cecilia Steen: With love,"- My dearest Jeffrey, I don't know when you'l...",Cecilia Steen,[redacted],"JE project <jeeproject@yahoo.com>, Jeffrey Eps...","Jul 25, 2019 9:16 AM","My dearest Jeffrey,\nI don't know when you'll ..."
2,HOUSE_OVERSIGHT_016203,Flipboard 10 for Today: 11 questions for Mueller,- Flipboard Interesting stories worth your ti...,Flipboard 10 for Today,editorialstaff@flipboard.com,jeevacation@gmail.com,"Jul 13, 2019 9:06 PM",Flipboard\nInteresting stories worth your time...
3,HOUSE_OVERSIGHT_028801,"Flipboard Week in Review: Alex Acosta resigns,...",- Flipboard Biggest news stories from the pa...,Flipboard Week in Review,editorialstaff@flipboard.com,jeevacation@gmail.com,"Jul 13, 2019 6:48 PM",Flipboard\nBiggest news stories from the past ...
4,HOUSE_OVERSIGHT_029504,[redacted]: [redacted],"- Dear Jeff, I read the news papers today, I ...",[redacted],[redacted],Jeffrey Epstein <jeevacation@gmail.com>,"Jul 10, 2019 8:07 AM","Dear Jeff,\nI read the news papers today, I ca..."

## Raw email profiling

Inspect the input before changing it. This makes later cleanup decisions and
their impact reproducible.

In [5]:
print(f"Raw emails: {len(raw_emails)}")
print(f"Unique senders: {raw_emails['from_email'].nunique()}")
print(f"Unique recipients: {raw_emails['to'].nunique()}")
print(raw_emails["body"].str.len().describe())

Raw emails: 14835
Unique senders: 455
Unique recipients: 1434
count     14835.000000
mean       1121.424065
std        6707.694938
min           1.000000
25%          84.000000
50%         377.000000
75%         893.000000
max      354403.000000
Name: body, dtype: float64

## Normalize email metadata and bodies

Metadata is collapsed to one line. Bodies preserve paragraph boundaries while
removing repeated spaces, tabs, and excessive blank lines. Missing values become
empty strings, never the literal text `"nan"`.

In [6]:
emails_normalized = normalize_email_fields(raw_emails)

normalization_examples = pd.DataFrame({
    "before": raw_emails["body"].head(5),
    "after": emails_normalized["body"].head(5),
})
display(normalization_examples)

,before,after
0,Lol good riddance,Lol good riddance
1,"My dearest Jeffrey,\nI don't know when you'll ...","My dearest Jeffrey,\nI don't know when you'll ..."
2,Flipboard\nInteresting stories worth your time...,Flipboard\nInteresting stories worth your time...
3,Flipboard\nBiggest news stories from the past ...,Flipboard\nBiggest news stories from the past ...
4,"Dear Jeff,\nI read the news papers today, I ca...","Dear Jeff,\nI read the news papers today, I ca..."

## Add email-only fields

Recipient counts and parsed dates are meaningful for email records only. They
are calculated before deduplication so the recipient list remains part of the
duplicate key.

In [7]:
emails_prepared = add_email_fields(emails_normalized)

print("Unparseable dates:", emails_prepared["parsed_date"].isna().sum())
print("Date range:", emails_prepared["parsed_date"].min(), "to", emails_prepared["parsed_date"].max())
display(
    emails_prepared[["to", "num_recipients"]]
    .sort_values("num_recipients", ascending=False)
    .head(20)
)

Unparseable dates: 0
Date range: 1970-01-01 00:00:00 to 2019-08-13 06:48:00

                                                      to  num_recipients
8437   valdemar iodice <valdemar@iodice.com.br>cc isa...              67
1617   Alan Rogers <[redacted]>, Jeffrey Epstein <jee...              34
6388   Allen West <[redacted]>, Rafael Bardaji <[reda...              31
12509  Allen West <[redacted]>, Rafael Bardaji <[reda...              31
6695   <sstrohaver@nlg.com>, <jboltax@nextjump.co>, <...              20
7016   Glenn Young <shakescenes@aol.com>, gm2127 <gm2...              20
6580   Gary Savitzky <rafael.prates@prismabrasil.com....              20
5748   Gary Savitzky <GarySavitzky@kamillagordon.oran...              20
5519   Schecter, Daniel (CC) <[redacted]>, Dunlavey, ...              17
8440   <JEEPROJECT@YAHOO.COM>cc <ehanna@nysgmail.com>...              16
5562   'Keough, Michael' <[redacted]>, King, Kathryn ...              13
5561   Will Bohlen <[redacted]>, King, Kathryn <[reda...              13
5559   Will Bohlen <[redacted]>, Miller, Michael <[re...              13
5557   Miller, Michael <[redacted]>, Katelyn Wohlford...              13
5564   Will Bohlen <[redacted]>, King, Kathryn <[reda...              13
5569   Will Bohlen <[redacted]>, Miller, Michael <[re...              13
5538   Dunlavey, Dean (OC) <[redacted]>cc Schecter, D...              13
5567   Miller, Michael <[redacted]>, Katelyn Wohlford...              13
5517   Dunlavey, Dean (OC) <[redacted]>, Schecter, Da...              13
5532   Dunlavey, Dean (OC) <[redacted]>, Schecter, Da...              13

## Email deduplication

Only emails are grouped by subject, sender, recipients, date, and normalized
body. All original document IDs are retained for citation.

In [8]:
dedup_key = email_dedup_key()
print("Full-row duplicates:", emails_prepared.duplicated().sum())
print("Content-based duplicates:", emails_prepared.duplicated(subset=dedup_key).sum())

duplicate_groups = duplicate_email_groups(emails_prepared)
display(duplicate_groups.head(10))

Full-row duplicates: 11
Content-based duplicates: 1211

,subject,from_email,to,num_recipients,date,body,n_rows,doc_ids,n_unique_doc_ids,n_unique_previews,n_unique_from_names
577,jeffrey E.: Re:,jeevacation@gmail.com,[redacted],1,"Sep 8, 2017 11:52 AM",what is your schedule in new york how long wil...,11,"[HOUSE_OVERSIGHT_032622, HOUSE_OVERSIGHT_02366...",11,10,1
578,jeffrey E.: Re:,jeevacation@gmail.com,[redacted],1,"Sep 8, 2017 1:33 PM",I will get larson to call you,11,"[HOUSE_OVERSIGHT_032622, HOUSE_OVERSIGHT_02366...",11,10,1
310,"Thomas Jr., Landon: Re: Saudi money",[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Oct 19, 2016 9:41 AM",Interesting. CEO of big finance form told me t...,9,"[HOUSE_OVERSIGHT_031511, HOUSE_OVERSIGHT_03163...",9,9,1
601,jeffrey E.: Re: Fwd:,[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Sep 19, 2014 6:15 AM","Agreed, but I need to be prepared to say yes b...",8,"[HOUSE_OVERSIGHT_023418, HOUSE_OVERSIGHT_02584...",8,8,1
594,jeffrey E.: Re: Fwd:,[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Sep 19, 2014 3:02 PM","Uh, yeah. We will now go through a period of s...",8,"[HOUSE_OVERSIGHT_023418, HOUSE_OVERSIGHT_02584...",8,8,1
604,jeffrey E.: Re: Fwd:,[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Sep 19, 2014 8:01 AM","Yes, trains exist -- people ride them to get f...",8,"[HOUSE_OVERSIGHT_023418, HOUSE_OVERSIGHT_02584...",8,8,1
603,jeffrey E.: Re: Fwd:,[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Sep 19, 2014 7:54 AM",Doesn't look like you are prioritizing your sc...,8,"[HOUSE_OVERSIGHT_023418, HOUSE_OVERSIGHT_02584...",8,8,1
602,jeffrey E.: Re: Fwd:,[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Sep 19, 2014 7:15 AM",Most girls do not have to worry about this crap.,8,"[HOUSE_OVERSIGHT_023418, HOUSE_OVERSIGHT_02584...",8,8,1
592,jeffrey E.: Re: Fwd:,[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Sep 19, 2014 2:57 PM",Reid's guy went down on all 7 counts.,8,"[HOUSE_OVERSIGHT_023418, HOUSE_OVERSIGHT_02584...",8,8,1
593,jeffrey E.: Re: Fwd:,[redacted],jeffrey E. <jeevacation@gmail.com>,1,"Sep 19, 2014 2:59 PM",Yep. And now he is a repeat offender.,8,"[HOUSE_OVERSIGHT_023418, HOUSE_OVERSIGHT_02584...",8,8,1

In [9]:
grouped_emails = deduplicate_emails(emails_prepared)
email_documents = emails_to_documents(grouped_emails)

print("Rows before grouping:", len(emails_prepared))
print("Email documents after grouping:", len(email_documents))
print("Rows collapsed:", len(emails_prepared) - len(email_documents))
email_documents.head()

Rows before grouping: 14835
Email documents after grouping: 13624
Rows collapsed: 1211

,source_ids,source_type,title,text,date,sender,recipients,page,n_original_rows
0,[a9daccc94ec91c8d1dc5f4f769c4d722],email,: !!! Re: Love from Prague,I guess....purity is easy here.. ;-)How is you...,"Jul 29, 2008 4:34 PM",petranemcova@mac.com,Jeffrey Epstein <jeeproject@yahoo.com>,<NA>,1
1,[a9daccc94ec91c8d1dc5f4f769c4d722],email,: !!! Re: Love from Prague,That we realize that we R all connected! That ...,"May 20, 2008 3:42 AM",petranemcova@mac.com,Jeffrey Epstein <jeeproject@yahoo.com>,<NA>,1
2,[2c3a88b2467a806c9bcf8789f75b165c],email,: (no subject),I am on a broken train and will be late. I cal...,"May 14, 2008 12:25 PM",9177492025@messaging.sprintpcs.com,<jeeproject@yahoo.com>,<NA>,1
3,[63e27cbc66fe426b5eb40e32b66b6665],email,: (no subject),"DL's package\n \n$105,000 salary\n$5,000 bonus...","Dec 5, 2007 6:42 PM",DKIESQ@aol.com,<jeeproject@yahoo.com>,<NA>,1
4,[63e27cbc66fe426b5eb40e32b66b6665],email,: (no subject),just - HI \nMarcia M.Who's never won? Biggest ...,"Jan 25, 2008 5:48 PM",Maemarcia@aol.com,<jeeproject@yahoo.com>,<NA>,1

## Load additional PDFs with OCR

PPStructureV3 reads each PDF directly with PP-OCRv6. Document orientation,
unwarping, text-line orientation, table, formula, chart, and seal recognition
are disabled. Layout regions only control reading order; every recognized text
line is retained regardless of its region label. Each
non-empty page becomes a document with a stable source ID such as
pdf:filename:p12.

The OCR cache is invalidated when a PDF or the OCR settings change. Inspect a
sample page before relying on PDF-derived answers.

In [10]:
pdf_documents = load_or_ocr_pdfs(
    PDF_DIR,
    OCR_PAGES_PATH,
    force=FORCE_RECOMPUTE_OCR,
)

print(f"OCR pages available: {len(pdf_documents)}")
if not pdf_documents.empty:
    display(pdf_documents[["source_ids", "title", "page", "text"]].head())

Creating model: ('PP-DocBlockLayout', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/yammo/.paddlex/official_models/PP-DocBlockLayout_safetensors`.

Loading weights:   0%|          | 0/889 [00:00<?, ?it/s]

Creating model: ('PP-DocLayout_plus-L', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/yammo/.paddlex/official_models/PP-DocLayout_plus-L_safetensors`.

Loading weights:   0%|          | 0/889 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_det', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/yammo/.paddlex/official_models/PP-OCRv6_medium_det_safetensors`.

Loading weights:   0%|          | 0/350 [00:00<?, ?it/s]

Creating model: ('PP-OCRv6_medium_rec', None, 'transformers')
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/yammo/.paddlex/official_models/PP-OCRv6_medium_rec_safetensors`.

Loading weights:   0%|          | 0/269 [00:00<?, ?it/s]

Processing Ghislaine-Maxwell-Deposition-Only-Transcript.pdf...
Processing Jeffrey Epstein Part 01 of 08_extracted_pages.pdf...
OCR pages available: 451

,source_ids,title,page,text
0,[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,Ghislaine-Maxwell-Deposition-Only-Transcript,1,Page 1 UNITED STATES DISTRICT COURT SOUTHERN D...
1,[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,Ghislaine-Maxwell-Deposition-Only-Transcript,2,Page 2 1 2 APPEARANCES: 3 BOIES SCHILLER & FLE...
2,[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,Ghislaine-Maxwell-Deposition-Only-Transcript,3,De3 1 2 THE VIDEOGRAPHER: We are now on 3 the ...
3,[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,Ghislaine-Maxwell-Deposition-Only-Transcript,4,Page 4 1 G Maxwell - Confidential 2 represent ...
4,[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,Ghislaine-Maxwell-Deposition-Only-Transcript,5,Page 5 1 G Maxwell - Confidential 2 of is that...

In [11]:
if not pdf_documents.empty:
    sample_page = pdf_documents.iloc[14] if len(pdf_documents) > 14 else pdf_documents.iloc[0]
    print(f"--- {sample_page['title']} (Page {sample_page['page']}) ---")
    print(sample_page["text"][:2500])

--- Ghislaine-Maxwell-Deposition-Only-Transcript (Page 15) ---
Page15 1 G Maxwell - Confidential 2 come to Jeffrey Epstein's home? 3 A. Again, there would be no course to 4 have a conversation with Virginia unless she 5 held herself out to be a masseuse. 6 Q. I'm not asking that question. I'm 7 asking if you invited her to come to Jeffrey 8 Epstein's home when she was under the age of 9 18? 10 A. Again, I repeat, she was a masseuse 11 and in the form and as my job, I was to have 12 people who he wanted for various things 13 including massage. She came as a masseuse. 14 Q. So you invited her to his home to 15 come to give a massage, is that correct? 16 MR. PAGLIUCA: Object to the form 17 and foundation. Misstates the witness' 18 testimony. 19 A. Again, I did not invite Virginia 20 Roberts. She came as a masseuse. 21 Q. She who invited her to come as a 22 masseuse, she just showed up at the front 23door? 24 MR. PAGLIUCA: Object to the form 25 and foundation.

MAGNAO LEGAL SERVICES

## Combine source-specific documents

Emails and PDF pages now share a small common schema. From this point onward,
chunking, embedding, retrieval, and citations are shared across source types.

In [12]:
documents_df = combine_documents(email_documents, pdf_documents)
print(documents_df.groupby("source_type").size())
display(documents_df.groupby("source_type")["text"].apply(lambda texts: texts.str.len().describe()))

source_type
email    13624
pdf        451
dtype: int64

source_type
email        count     13624.000000
             mean       1130.576923
             std        6838.900183
             min           1.000000
             25%         108.000000
             50%         449.000000
             75%         956.250000
             max      354398.000000
pdf          count       451.000000
             mean        947.942350
             std         614.112387
             min          55.000000
             25%         807.000000
             50%         875.000000
             75%         927.500000
             max        7027.000000
Name: text, dtype: float64

# **CHUNKING**

Each chunk receives a source-aware header. Email headers preserve sender,
recipient, date, and source IDs; PDF headers preserve document title, page, and
source IDs. The chunk cache is invalidated when documents or chunk settings
change.

In [13]:
tokenizer = AutoTokenizer.from_pretrained(EMBEDDING_MODEL_ID)

chunks_df = load_or_build_chunks(
    documents_df,
    tokenizer,
    CHUNKS_PATH,
    force=FORCE_RECOMPUTE_CHUNKS,
    max_tokens=MAX_CHUNK_TOKENS,
)
chunks_df.head()

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (842 > 512). Running this sequence through the model will result in indexing errors

,chunk_id,document_index,chunk_index,num_chunks,source_ids,source_type,title,date,page,text
0,0_0,0,0,9,[a9daccc94ec91c8d1dc5f4f769c4d722],email,: !!! Re: Love from Prague,"Jul 29, 2008 4:34 PM",<NA>,Type: Email\nSubject: : !!! Re: Love from Prag...
1,0_1,0,1,9,[a9daccc94ec91c8d1dc5f4f769c4d722],email,: !!! Re: Love from Prague,"Jul 29, 2008 4:34 PM",<NA>,Type: Email\nSubject: : !!! Re: Love from Prag...
2,0_2,0,2,9,[a9daccc94ec91c8d1dc5f4f769c4d722],email,: !!! Re: Love from Prague,"Jul 29, 2008 4:34 PM",<NA>,Type: Email\nSubject: : !!! Re: Love from Prag...
3,0_3,0,3,9,[a9daccc94ec91c8d1dc5f4f769c4d722],email,: !!! Re: Love from Prague,"Jul 29, 2008 4:34 PM",<NA>,Type: Email\nSubject: : !!! Re: Love from Prag...
4,0_4,0,4,9,[a9daccc94ec91c8d1dc5f4f769c4d722],email,: !!! Re: Love from Prague,"Jul 29, 2008 4:34 PM",<NA>,Type: Email\nSubject: : !!! Re: Love from Prag...

In [14]:
chunk_token_counts = chunks_df["text"].map(
    lambda text: len(tokenizer.encode(text, add_special_tokens=True))
)
print(f"Chunk count: {len(chunks_df)}")
print(f"Longest chunk: {chunk_token_counts.max()} tokens")
assert chunk_token_counts.max() <= MAX_CHUNK_TOKENS

Chunk count: 25114
Longest chunk: 507 tokens

# **RETRIEVAL METHODS**

Two retrieval methods are kept separate so their effect can be compared directly:

1. **Dense baseline:** embed the complete question and return the nearest FAISS chunks.
2. **Hybrid:** take the union of dense top 20 and TF-IDF top 20, rerank the
   candidates against the complete question, retain five anchors, and add one
   neighboring chunk on each side where space permits.

Both methods receive the same original question. The generative LLM is used only
after retrieval.

In [15]:
embedding_model = load_embedding_model(EMBEDDING_MODEL_ID, device)
embeddings = load_or_compute_embeddings(
    chunks_df,
    embedding_model,
    EMBEDDINGS_PATH,
    model_id=EMBEDDING_MODEL_ID,
    force=FORCE_RECOMPUTE_EMBEDDINGS,
)
dense_index = build_index(embeddings)
tfidf_vectorizer, tfidf_matrix = build_tfidf_index(chunks_df)
reranker = load_reranker(RERANKER_MODEL_ID, device)

assert embeddings.shape[0] == len(chunks_df) == dense_index.ntotal
assert tfidf_matrix.shape[0] == len(chunks_df)
print("Embedding shape:", embeddings.shape)
print("TF-IDF shape:", tfidf_matrix.shape)


def retrieve_dense_method(query, k=5):
    return retrieve_dense(query, embedding_model, dense_index, chunks_df, k=k)


def retrieve_hybrid_method(query, k=MAX_CONTEXT_CHUNKS):
    return retrieve_hybrid(
        query,
        embedding_model,
        dense_index,
        tfidf_vectorizer,
        tfidf_matrix,
        reranker,
        chunks_df,
        dense_k=DENSE_CANDIDATES,
        tfidf_k=TFIDF_CANDIDATES,
        rerank_k=RERANKED_ANCHORS,
        neighbors=NEIGHBORS,
        max_chunks=k,
    )

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/393 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Embedding shape: (25114, 768)
TF-IDF shape: (25114, 824712)

In [16]:
example_query = "What was discussed regarding Saudi money?"
dense_example_evidence = retrieve_dense_method(example_query)
hybrid_example_evidence = retrieve_hybrid_method(example_query)

print("Dense baseline")
display(dense_example_evidence[["source_type", "source_ids", "title", "page", "score"]])

print("Hybrid retrieve-rerank-neighbors")
display(
    hybrid_example_evidence[
        ["source_type", "source_ids", "title", "page", "retrieval_role", "score"]
    ]
)

Dense baseline

,source_type,source_ids,title,page,score
20046,email,[HOUSE_OVERSIGHT_031504],"Thomas Jr., Landon: Re: Saudi money",<NA>,0.770566
20043,email,[HOUSE_OVERSIGHT_031496],"Thomas Jr., Landon: Re: Saudi money",<NA>,0.769485
20051,email,"[HOUSE_OVERSIGHT_031507, HOUSE_OVERSIGHT_03151...","Thomas Jr., Landon: Re: Saudi money",<NA>,0.766614
20050,email,"[HOUSE_OVERSIGHT_031504, HOUSE_OVERSIGHT_03150...","Thomas Jr., Landon: Re: Saudi money",<NA>,0.761554
20071,email,"[HOUSE_OVERSIGHT_031501, HOUSE_OVERSIGHT_03150...","Thomas Jr., Landon: Re: Saudi money",<NA>,0.756631

Hybrid retrieve-rerank-neighbors

,source_type,source_ids,title,page,retrieval_role,score
0,email,[HOUSE_OVERSIGHT_031622],"Thomas Jr., Landon: Re: Saudi money",<NA>,anchor,-0.237445
1,email,[HOUSE_OVERSIGHT_031511],"Thomas Jr., Landon: Re: Saudi money",<NA>,anchor,-0.318612
2,email,[HOUSE_OVERSIGHT_031496],"Thomas Jr., Landon: Re: Saudi money",<NA>,anchor,-0.394367
3,email,[HOUSE_OVERSIGHT_031504],"Thomas Jr., Landon: Re: Saudi money",<NA>,anchor,-0.419556
4,email,[HOUSE_OVERSIGHT_031631],"Thomas Jr., Landon: Re: Saudi money",<NA>,anchor,-0.426019

# **PROMPT ENGINEERING**

The prompt uses only retrieved source segments. It requires source-document ID
citations and explicitly asks the model to say when evidence is unavailable.

In [17]:
example_prompt = build_prompt(example_query, hybrid_example_evidence)
print(f"Prompt length: {len(example_prompt)} characters")
print(example_prompt[:1000] + "...")

Prompt length: 3212 characters
<start_of_turn>user
You are an investigative assistant analyzing source documents from the Epstein files. Answer using ONLY the provided source segments. For each factual claim, cite the 'Source document IDs' in the segment headers. If the evidence does not contain the answer, state that it is not available in the retrieved data. Do not speculate.

RELEVANT SOURCE SEGMENTS:
[Segment 1]
Type: Email
Subject: Thomas Jr., Landon: Re: Saudi money
From: jeffrey E. <jeevacation@gmail.com>
To: Thomas Jr., Landon <[redacted]>
Date: Oct 19, 2016 1:43 PM
Source document IDs: HOUSE_OVERSIGHT_031622

Body chunk 1 of 1:
most of the saudi money is tied up in pe funds. no withdrawals allowed. and im not seeing much in the secondary market.. blackrock is more money market, more like custodian than investor.

[Segment 2]
Type: Email
Subject: Thomas Jr., Landon: Re: Saudi money
From: jeffrey E. <jeevacation@gmail.com>
To: Thomas Jr., Landon <[redacted]>
Date: Oct 19, 2016 9:43 AM
Source document IDs: HOU...

# **MODEL LOADING AND GENERATION**

Gemma is loaded from a GGUF file through llama-cpp-python. The notebook keeps
the short question-answering composition visible while the retrieval mechanics
remain in rag.py.

In [18]:
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()

HF_TOKEN = get_secret("HF_TOKEN", "Enter Hugging Face Token (required for gated Gemma access): ")
LLM_MODEL_ID = "igorls/gemma-4-E4B-it-heretic-GGUF"
LLM_FILENAME = "gemma-4-E4B-it-heretic-Q4_K_M.gguf"

llm = load_llm(LLM_MODEL_ID, LLM_FILENAME, HF_TOKEN, gpu_offload=llama_cpp_gpu)

/home/yammo/miniconda3/envs/epstein-rag/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `hf_hub_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
llama_model_loader: loaded meta data with 45 key-value pairs and 720 tensors from /home/yammo/.cache/huggingface/hub/models--igorls--gemma-4-E4B-it-heretic-GGUF/snapshots/8ad01b5431d70143b0eb8de76b58bb4556dc0d52/./gemma-4-E4B-it-heretic-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma4
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                     general.sampling.top_k i32              = 64
llama_model_loader: - kv   3:                     general.sampling.top_p f32              = 0.950000
llama_model_loader: - kv   4:                      general.sampling.temp f32              = 1.000000
llama_model_loader: - kv   5:                               general.name str              = Unsloth_Merged
llama_model_loader: - kv   6:                       general.quantized_by str              = Unsloth
llama_model_loader: - kv   7:                         general.size_label str              = 7.5B
llama_model_loader: - kv   8:                           general.repo_url str              = https://huggingface.co/unsloth
llama_model_loader: - kv   9:                               general.tags arr[str,2]       = ["unsloth", "llama.cpp"]
llama_model_loader: - kv  10:                         gemma4.block_count u32              = 42
llama_model_loader: - kv  11:                      gemma4.context_length u32              = 131072
llama_model_loader: - kv  12:                    gemma4.embedding_length u32              = 2560
llama_model_loader: - kv  13:                 gemma4.feed_forward_length u32              = 10240
llama_model_loader: - kv  14:                gemma4.attention.head_count u32              = 8
llama_model_loader: - kv  15:             gemma4.attention.head_count_kv u32              = 2
llama_model_loader: - kv  16:                      gemma4.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  17:                  gemma4.rope.freq_base_swa f32              = 10000.000000
llama_model_loader: - kv  18:    gemma4.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  19:                gemma4.attention.key_length u32              = 512
llama_model_loader: - kv  20:              gemma4.attention.value_length u32              = 512
llama_model_loader: - kv  21:             gemma4.final_logit_softcapping f32              = 30.000000
llama_model_loader: - kv  22:            gemma4.attention.sliding_window u32              = 512
llama_model_loader: - kv  23:          gemma4.attention.shared_kv_layers u32              = 18
llama_model_loader: - kv  24:    gemma4.embedding_length_per_layer_input u32              = 256
llama_model_loader: - kv  25:    gemma4.attention.sliding_window_pattern arr[bool,42]     = [true, true, true, true, true, false,...
llama_model_loader: - kv  26:            gemma4.attention.key_length_swa u32              = 256
llama_model_loader: - kv  27:          gemma4.attention.value_length_swa u32              = 256
llama_model_loader: - kv  28:                gemma4.rope.dimension_count u32              = 512
llama_model_loader: - kv  29:            gemma4.rope.dimension_count_swa u32              = 256
llama_model_loader: - kv  30:                       tokenizer.ggml.model str              = gemma4
llama_model_loader: - kv  31:                      tokenizer.ggml.tokens arr[str,262144]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  32:                      tokenizer.ggml.scores arr[f32,262144]  = [-1000.000000, -1000.000000, -1000.00...
llama_model_loader: - kv  33:                  tokenizer.ggml.token_type arr[i32,262144]  = [3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  34:                      tokenizer.ggml.merges arr[str,514906]  = ["\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n", ...
llama_model_loader: - kv  35:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  36:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  37:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  38:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  39:               tokenizer.ggml.mask_token_id u32              = 4
llama_model_loader: - kv  40:                    tokenizer.chat_template str              = {%- macro format_parameters(propertie...
llama_model_loader: - kv  41:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - kv  42:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  43:               general.quantization_version u32              = 2
llama_model_loader: - kv  44:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  339 tensors
llama_model_loader: - type q4_K:  336 tensors
llama_model_loader: - type q6_K:   44 tensors
llama_model_loader: - type bf16:    1 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 4.95 GiB (5.66 BPW)
llama_prepare_model_devices: using device CUDA0 (NVIDIA GeForce RTX 2070) (0000:01:00.0) - 6566 MiB free
init_tokenizer: initializing tokenizer for type 2
load: override 'tokenizer.ggml.add_bos_token' to 'true' for Gemma4
load: 0 unused tokens
load: control token: 255999 '<|image>' is not marked as EOG
load: control token: 258882 '<image|>' is not marked as EOG
load: control token: 258883 '<audio|>' is not marked as EOG
load: control token:     98 '<|think|>' is not marked as EOG
load: control token:    105 '<|turn>' is not marked as EOG
load: control token: 258880 '<|image|>' is not marked as EOG
load: control token:      2 '<bos>' is not marked as EOG
load: control-looking token:    212 '</s>' was not control-type; this is probably a bug in the model. its type will be overridden
load: control token:      0 '<pad>' is not marked as EOG
load: control-looking token:     50 '<|tool_response>' was not control-type; this is probably a bug in the model. its type will be overridden
load: control token:     46 '<|tool>' is not marked as EOG
load: control token:     47 '<tool|>' is not marked as EOG
load: control token: 256000 '<|audio>' is not marked as EOG
load: control token:      3 '<unk>' is not marked as EOG
load: control token: 258881 '<|audio|>' is not marked as EOG
load: control token:      4 '<mask>' is not marked as EOG
load: printing all EOG tokens:
load:   - 1 ('<eos>')
load:   - 50 ('<|tool_response>')
load:   - 106 ('<turn|>')
load:   - 212 ('</s>')
load: special_eog_ids contains '<|tool_response>', removing '</s>' token from EOG list
load: special tokens cache size = 23
load: token to piece cache size = 1.9445 MB
print_info: arch                  = gemma4
print_info: vocab_only            = 0
print_info: no_alloc              = 0
print_info: n_ctx_train           = 131072
print_info: n_embd_inp            = 2560
print_info: n_embd                = 2560
print_info: n_embd_out            = 2560
print_info: n_layer               = 42
print_info: n_layer_all           = 42
print_info: n_head                = 8
print_info: n_head_kv             = 2
print_info: n_rot                 = 512
print_info: n_swa                 = 512
print_info: is_swa_any            = 1
print_info: n_embd_head_k         = 512
print_info: n_embd_head_v         = 512
print_info: n_gqa                 = 4
print_info: n_embd_k_gqa          = [512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024]
print_info: n_embd_v_gqa          = [512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024, 512, 512, 512, 512, 512, 1024]
print_info: f_norm_eps            = 0.0e+00
print_info: f_norm_rms_eps        = 1.0e-06
print_info: f_clamp_kqv           = 0.0e+00
print_info: f_max_alibi_bias      = 0.0e+00
print_info: f_logit_scale         = 0.0e+00
print_info: f_attn_scale          = 1.0e+00
print_info: f_attn_value_scale    = 0.0000
print_info: n_ff                  = 10240
print_info: n_expert              = 0
print_info: n_expert_used         = 0
print_info: n_expert_groups       = 0
print_info: n_group_used          = 0
print_info: causal attn           = 1
print_info: pooling type          = -1
print_info: rope type             = 2
print_info: rope scaling          = linear
print_info: freq_base_train       = 1000000.0
print_info: freq_scale_train      = 1
print_info: freq_base_swa         = 10000.0
print_info: freq_scale_swa        = 1
print_info: n_embd_head_k_swa     = 256
print_info: n_embd_head_v_swa     = 256
print_info: n_rot_swa             = 256
print_info: n_ctx_orig_yarn       = 131072
print_info: rope_yarn_log_mul     = 0.0000
print_info: rope_finetuned        = unknown
print_info: model type            = E4B
print_info: model params          = 7.52 B
print_info: general.name          = Unsloth_Merged
print_info: vocab type            = BPE
print_info: n_vocab               = 262144
print_info: n_merges              = 514906
print_info: BOS token             = 2 '<bos>'
print_info: EOS token             = 1 '<eos>'
print_info: UNK token             = 3 '<unk>'
print_info: PAD token             = 0 '<pad>'
print_info: MASK token            = 4 '<mask>'
print_info: LF token              = 107 '
'
print_info: EOG token             = 1 '<eos>'
print_info: EOG token             = 50 '<|tool_response>'
print_info: EOG token             = 106 '<turn|>'
print_info: max token length      = 93
load_tensors: loading model tensors, this can take a while... (mmap = true, direct_io = false)
load_tensors: layer   0 assigned to device CUDA0, is_swa = 1
load_tensors: layer   1 assigned to device CUDA0, is_swa = 1
load_tensors: layer   2 assigned to device CUDA0, is_swa = 1
load_tensors: layer   3 assigned to device CUDA0, is_swa = 1
load_tensors: layer   4 assigned to device CUDA0, is_swa = 1
load_tensors: layer   5 assigned to device CUDA0, is_swa = 0
load_tensors: layer   6 assigned to device CUDA0, is_swa = 1
load_tensors: layer   7 assigned to device CUDA0, is_swa = 1
load_tensors: layer   8 assigned to device CUDA0, is_swa = 1
load_tensors: layer   9 assigned to device CUDA0, is_swa = 1
load_tensors: layer  10 assigned to device CUDA0, is_swa = 1
load_tensors: layer  11 assigned to device CUDA0, is_swa = 0
load_tensors: layer  12 assigned to device CUDA0, is_swa = 1
load_tensors: layer  13 assigned to device CUDA0, is_swa = 1
load_tensors: layer  14 assigned to device CUDA0, is_swa = 1
load_tensors: layer  15 assigned to device CUDA0, is_swa = 1
load_tensors: layer  16 assigned to device CUDA0, is_swa = 1
load_tensors: layer  17 assigned to device CUDA0, is_swa = 0
load_tensors: layer  18 assigned to device CUDA0, is_swa = 1
load_tensors: layer  19 assigned to device CUDA0, is_swa = 1
load_tensors: layer  20 assigned to device CUDA0, is_swa = 1
load_tensors: layer  21 assigned to device CUDA0, is_swa = 1
load_tensors: layer  22 assigned to device CUDA0, is_swa = 1
load_tensors: layer  23 assigned to device CUDA0, is_swa = 0
load_tensors: layer  24 assigned to device CUDA0, is_swa = 1
load_tensors: layer  25 assigned to device CUDA0, is_swa = 1
load_tensors: layer  26 assigned to device CUDA0, is_swa = 1
load_tensors: layer  27 assigned to device CUDA0, is_swa = 1
load_tensors: layer  28 assigned to device CUDA0, is_swa = 1
load_tensors: layer  29 assigned to device CUDA0, is_swa = 0
load_tensors: layer  30 assigned to device CUDA0, is_swa = 1
load_tensors: layer  31 assigned to device CUDA0, is_swa = 1
load_tensors: layer  32 assigned to device CUDA0, is_swa = 1
load_tensors: layer  33 assigned to device CUDA0, is_swa = 1
load_tensors: layer  34 assigned to device CUDA0, is_swa = 1
load_tensors: layer  35 assigned to device CUDA0, is_swa = 0
load_tensors: layer  36 assigned to device CUDA0, is_swa = 1
load_tensors: layer  37 assigned to device CUDA0, is_swa = 1
load_tensors: layer  38 assigned to device CUDA0, is_swa = 1
load_tensors: layer  39 assigned to device CUDA0, is_swa = 1
load_tensors: layer  40 assigned to device CUDA0, is_swa = 1
load_tensors: layer  41 assigned to device CUDA0, is_swa = 0
load_tensors: layer  42 assigned to device CUDA0, is_swa = 0
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor per_layer_token_embd.weight
create_tensor: loading tensor per_layer_model_proj.weight
create_tensor: loading tensor per_layer_proj_norm.weight
create_tensor: loading tensor output_norm.weight
create_tensor: loading tensor blk.0.attn_norm.weight
create_tensor: loading tensor blk.0.attn_q.weight
create_tensor: loading tensor blk.0.attn_k.weight
create_tensor: loading tensor blk.0.attn_v.weight
create_tensor: loading tensor blk.0.attn_output.weight
create_tensor: loading tensor blk.0.attn_q_norm.weight
create_tensor: loading tensor blk.0.attn_k_norm.weight
create_tensor: loading tensor blk.0.post_attention_norm.weight
create_tensor: loading tensor blk.0.layer_output_scale.weight
create_tensor: loading tensor blk.0.ffn_norm.weight
create_tensor: loading tensor blk.0.ffn_gate.weight
create_tensor: loading tensor blk.0.ffn_up.weight
create_tensor: loading tensor blk.0.ffn_down.weight
create_tensor: loading tensor blk.0.post_ffw_norm.weight
create_tensor: loading tensor blk.0.inp_gate.weight
create_tensor: loading tensor blk.0.proj.weight
create_tensor: loading tensor blk.0.post_norm.weight
create_tensor: loading tensor blk.1.attn_norm.weight
create_tensor: loading tensor blk.1.attn_q.weight
create_tensor: loading tensor blk.1.attn_k.weight
create_tensor: loading tensor blk.1.attn_v.weight
create_tensor: loading tensor blk.1.attn_output.weight
create_tensor: loading tensor blk.1.attn_q_norm.weight
create_tensor: loading tensor blk.1.attn_k_norm.weight
create_tensor: loading tensor blk.1.post_attention_norm.weight
create_tensor: loading tensor blk.1.layer_output_scale.weight
create_tensor: loading tensor blk.1.ffn_norm.weight
create_tensor: loading tensor blk.1.ffn_gate.weight
create_tensor: loading tensor blk.1.ffn_up.weight
create_tensor: loading tensor blk.1.ffn_down.weight
create_tensor: loading tensor blk.1.post_ffw_norm.weight
create_tensor: loading tensor blk.1.inp_gate.weight
create_tensor: loading tensor blk.1.proj.weight
create_tensor: loading tensor blk.1.post_norm.weight
create_tensor: loading tensor blk.2.attn_norm.weight
create_tensor: loading tensor blk.2.attn_q.weight
create_tensor: loading tensor blk.2.attn_k.weight
create_tensor: loading tensor blk.2.attn_v.weight
create_tensor: loading tensor blk.2.attn_output.weight
create_tensor: loading tensor blk.2.attn_q_norm.weight
create_tensor: loading tensor blk.2.attn_k_norm.weight
create_tensor: loading tensor blk.2.post_attention_norm.weight
create_tensor: loading tensor blk.2.layer_output_scale.weight
create_tensor: loading tensor blk.2.ffn_norm.weight
create_tensor: loading tensor blk.2.ffn_gate.weight
create_tensor: loading tensor blk.2.ffn_up.weight
create_tensor: loading tensor blk.2.ffn_down.weight
create_tensor: loading tensor blk.2.post_ffw_norm.weight
create_tensor: loading tensor blk.2.inp_gate.weight
create_tensor: loading tensor blk.2.proj.weight
create_tensor: loading tensor blk.2.post_norm.weight
create_tensor: loading tensor blk.3.attn_norm.weight
create_tensor: loading tensor blk.3.attn_q.weight
create_tensor: loading tensor blk.3.attn_k.weight
create_tensor: loading tensor blk.3.attn_v.weight
create_tensor: loading tensor blk.3.attn_output.weight
create_tensor: loading tensor blk.3.attn_q_norm.weight
create_tensor: loading tensor blk.3.attn_k_norm.weight
create_tensor: loading tensor blk.3.post_attention_norm.weight
create_tensor: loading tensor blk.3.layer_output_scale.weight
create_tensor: loading tensor blk.3.ffn_norm.weight
create_tensor: loading tensor blk.3.ffn_gate.weight
create_tensor: loading tensor blk.3.ffn_up.weight
create_tensor: loading tensor blk.3.ffn_down.weight
create_tensor: loading tensor blk.3.post_ffw_norm.weight
create_tensor: loading tensor blk.3.inp_gate.weight
create_tensor: loading tensor blk.3.proj.weight
create_tensor: loading tensor blk.3.post_norm.weight
create_tensor: loading tensor blk.4.attn_norm.weight
create_tensor: loading tensor blk.4.attn_q.weight
create_tensor: loading tensor blk.4.attn_k.weight
create_tensor: loading tensor blk.4.attn_v.weight
create_tensor: loading tensor blk.4.attn_output.weight
create_tensor: loading tensor blk.4.attn_q_norm.weight
create_tensor: loading tensor blk.4.attn_k_norm.weight
create_tensor: loading tensor blk.4.post_attention_norm.weight
create_tensor: loading tensor blk.4.layer_output_scale.weight
create_tensor: loading tensor blk.4.ffn_norm.weight
create_tensor: loading tensor blk.4.ffn_gate.weight
create_tensor: loading tensor blk.4.ffn_up.weight
create_tensor: loading tensor blk.4.ffn_down.weight
create_tensor: loading tensor blk.4.post_ffw_norm.weight
create_tensor: loading tensor blk.4.inp_gate.weight
create_tensor: loading tensor blk.4.proj.weight
create_tensor: loading tensor blk.4.post_norm.weight
create_tensor: loading tensor blk.5.attn_norm.weight
create_tensor: loading tensor blk.5.attn_q.weight
create_tensor: loading tensor blk.5.attn_k.weight
create_tensor: loading tensor blk.5.attn_v.weight
create_tensor: loading tensor blk.5.attn_output.weight
create_tensor: loading tensor blk.5.attn_q_norm.weight
create_tensor: loading tensor blk.5.attn_k_norm.weight
create_tensor: loading tensor blk.5.post_attention_norm.weight
create_tensor: loading tensor blk.5.layer_output_scale.weight
create_tensor: loading tensor rope_freqs.weight
create_tensor: loading tensor blk.5.ffn_norm.weight
create_tensor: loading tensor blk.5.ffn_gate.weight
create_tensor: loading tensor blk.5.ffn_up.weight
create_tensor: loading tensor blk.5.ffn_down.weight
create_tensor: loading tensor blk.5.post_ffw_norm.weight
create_tensor: loading tensor blk.5.inp_gate.weight
create_tensor: loading tensor blk.5.proj.weight
create_tensor: loading tensor blk.5.post_norm.weight
create_tensor: loading tensor blk.6.attn_norm.weight
create_tensor: loading tensor blk.6.attn_q.weight
create_tensor: loading tensor blk.6.attn_k.weight
create_tensor: loading tensor blk.6.attn_v.weight
create_tensor: loading tensor blk.6.attn_output.weight
create_tensor: loading tensor blk.6.attn_q_norm.weight
create_tensor: loading tensor blk.6.attn_k_norm.weight
create_tensor: loading tensor blk.6.post_attention_norm.weight
create_tensor: loading tensor blk.6.layer_output_scale.weight
create_tensor: loading tensor blk.6.ffn_norm.weight
create_tensor: loading tensor blk.6.ffn_gate.weight
create_tensor: loading tensor blk.6.ffn_up.weight
create_tensor: loading tensor blk.6.ffn_down.weight
create_tensor: loading tensor blk.6.post_ffw_norm.weight
create_tensor: loading tensor blk.6.inp_gate.weight
create_tensor: loading tensor blk.6.proj.weight
create_tensor: loading tensor blk.6.post_norm.weight
create_tensor: loading tensor blk.7.attn_norm.weight
create_tensor: loading tensor blk.7.attn_q.weight
create_tensor: loading tensor blk.7.attn_k.weight
create_tensor: loading tensor blk.7.attn_v.weight
create_tensor: loading tensor blk.7.attn_output.weight

In [19]:
def answer_question(query, retrieve_question, k, max_new_tokens=1024):
    evidence = retrieve_question(query, k)
    prompt = build_prompt(query, evidence)
    return generate_answer(llm, prompt, max_new_tokens=max_new_tokens)


def answer_dense(query, max_new_tokens=1024):
    return answer_question(query, retrieve_dense_method, 5, max_new_tokens)


def answer_hybrid(query, max_new_tokens=1024):
    return answer_question(
        query,
        retrieve_hybrid_method,
        MAX_CONTEXT_CHUNKS,
        max_new_tokens,
    )


query = "What are the main discussions regarding the Saudi contract and who was involved?"
print(answer_hybrid(query))

ggml_cuda_graph_set_enabled: disabling CUDA graphs due to GPU architecture
llama_perf_context_print:        load time =    2211.62 ms
llama_perf_context_print: prompt eval time =    2209.77 ms /  2988 tokens (    0.74 ms per token,  1352.18 tokens per second)
llama_perf_context_print:        eval time =    6505.11 ms /   281 runs   (   23.15 ms per token,    43.20 tokens per second)
llama_perf_context_print:       total time =    8962.04 ms /  3269 tokens
llama_perf_context_print:    graphs reused =        279

The main discussions regarding the Saudi contract include:

*   A **$110bn arms package** announced during US President Donald Trump's first foreign trip stop in Saudi Arabia, which the White House hopes will help Saudi Arabia and other gulf states combat terrorism and ward off threats from Iran (Segment 1, Segment 3).
*   The **separate deal with Blackstone** to establish a fund for US infrastructure (Segment 1, Segment 3).
*   The **sovereign Public Investment Fund** intending to invest **$20bn** into Blackstone's new vehicle, with a further **$20bn** coming from other investors (Segment 1, Segment 3).

The parties involved include:

*   **US President Donald Trump** (Segment 1, Segment 3).
*   **Saudi Arabia** (Segment 1, Segment 3).
*   **The White House** (Segment 1, Segment 3).
*   **Blackstone** (Segment 1, Segment 3).
*   **The sovereign Public Investment Fund** (Segment 1, Segment 3).
*   **Richard John Nawrot**, **Terje Rod-Larsen**, **George Henderson**, and **Andreas Kraus** (as recipients/participants in the email discussions) (Segment 1, Segment 3).

# **TESTING AND EVALUATION**

The configured API provider generates a reproducible, source-grounded 16-case test set: eight
questions from OCR PDF pages and eight from emails. It then judges RAG answers for accuracy,
faithfulness, and citations. Cached results are
used unless recomputation is requested.

In [20]:
api_key_name = "GOOGLE_API_KEY" if EVALUATION_PROVIDER == "gemini" else "OPENROUTER_API_KEY"
evaluation_api_key = get_secret(
    api_key_name,
    f"Enter {EVALUATION_PROVIDER} API key (or press Enter to use cached results): ",
)
evaluation_text = make_text_generator(
    EVALUATION_PROVIDER,
    EVALUATION_MODEL,
    evaluation_api_key,
)

In [21]:
micro_test_set = generate_ground_truth(
    documents_df,
    evaluation_text,
    TEST_SET_PATH,
    force=FORCE_RECOMPUTE_TEST_SET,
    n=MICRO_TEST_SET_SIZE,
    request_delay=EVALUATION_REQUEST_DELAY,
)
print(f"Test set ready with {len(micro_test_set)} Q/A pairs.")

Test set ready with 16 Q/A pairs.

### Retrieval evaluation

The same test questions are run through both retrieval methods. Recall@5, @8,
and @10 therefore show whether the hybrid method improves source discovery
before answer quality is judged. This remains a source-level metric: a hit does
not prove that the returned chunk contains the answer.

In [22]:
dense_retrieval_report = evaluate_retrieval(
    micro_test_set,
    retrieve_dense_method,
)
hybrid_retrieval_report = evaluate_retrieval(
    micro_test_set,
    retrieve_hybrid_method,
)

retrieval_summary = pd.DataFrame(
    {
        "method": ["Dense baseline", "Hybrid"],
        **{
            f"Recall@{k}": [
                dense_retrieval_report[f"hit_at_{k}"].mean(),
                hybrid_retrieval_report[f"hit_at_{k}"].mean(),
            ]
            for k in (5, 8, 10)
        },
    }
)
display(retrieval_summary)

retrieval_comparison = dense_retrieval_report[
    ["question", "first_hit_rank"]
].rename(columns={"first_hit_rank": "dense_first_hit_rank"})
retrieval_comparison["hybrid_first_hit_rank"] = hybrid_retrieval_report[
    "first_hit_rank"
]
display(retrieval_comparison)

           method  Recall@5  Recall@8  Recall@10
0  Dense baseline     0.625    0.8125     0.8125
1          Hybrid     0.875    0.8750     0.8750

,question,dense_first_hit_rank,hybrid_first_hit_rank
0,What was the amount Epstein donated to Democra...,2.0,1.0
1,What is the date and title of the email from M...,1.0,1.0
2,What charges did Palm Beach police seek agains...,2.0,1.0
3,"In the email about work orders for LSJ, what a...",7.0,1.0
4,What discount is offered for a 26-week digital...,NaN,4.0
5,Why did JE request a Friday flight for a frien...,1.0,1.0
6,Which company and city did Mark Patzelt repres...,NaN,2.0
7,What did Marcus go to the house to measure for...,4.0,1.0
8,When Epstein was indicted on felony solicitati...,8.0,NaN
9,"Who stated that the 98,776-acre parcel is the ...",1.0,1.0
10,What was Jeffrey Epstein's bond amount after h...,1.0,1.0
11,"Which positions did Maxwell say she hired for,...",7.0,NaN
12,"What maximum width did JE set for the console,...",1.0,1.0
13,"Who sent the email on January 14, 2008, with t...",1.0,1.0
14,Which 53-year-old Manhattan money manager was ...,NaN,2.0
15,Which Harvard law professor provided MySpace.c...,3.0,4.0

### Generation evaluation

Evaluates end-to-end answer generation quality for both dense and hybrid RAG pipelines using the evaluator LLM. Each generated response is judged against reference gold answers and source document IDs for factual accuracy, faithfulness, and citation accuracy.

In [23]:
dense_answer_results = evaluate_answers(
    micro_test_set,
    answer_dense,
    evaluation_text,
    DENSE_EVALUATION_PATH,
    force=FORCE_RECOMPUTE_EVALUATION,
    request_delay=EVALUATION_REQUEST_DELAY,
)
hybrid_answer_results = evaluate_answers(
    micro_test_set,
    answer_hybrid,
    evaluation_text,
    HYBRID_EVALUATION_PATH,
    force=FORCE_RECOMPUTE_EVALUATION,
    request_delay=EVALUATION_REQUEST_DELAY,
)

answer_frames = []
if dense_answer_results:
    answer_frames.append(
        pd.DataFrame(dense_answer_results).assign(method="Dense baseline")
    )
if hybrid_answer_results:
    answer_frames.append(
        pd.DataFrame(hybrid_answer_results).assign(method="Hybrid")
    )

if answer_frames:
    answer_comparison = pd.concat(answer_frames, ignore_index=True)
    display(answer_comparison.groupby("method", as_index=False)["score"].mean())
    display(answer_comparison)
else:
    print("No evaluation results available. Provide an API key or use cached results.")

           method   score
0  Dense baseline  6.1250
1          Hybrid  8.5625

,question,gold,source_ids,rag,score,reasoning,method
0,What was the amount Epstein donated to Democra...,"He donated more than $100,000 to Democratic ca...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,"Epstein donated more than $100,000 to Democrat...",7,The system answer accurately states the donati...,Dense baseline
1,What is the date and title of the email from M...,"The email is dated Friday March 11, 2011, titl...",[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,The email from Maxwell to Jeffrey is dated **F...,9,The system answer is accurate and faithful to ...,Dense baseline
2,What charges did Palm Beach police seek agains...,"On May 1, police sought warrants to arrest Eps...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,"On May 1, the department asked prosecutors to ...",9,The System Answer accurately matches the Gold ...,Dense baseline
3,"In the email about work orders for LSJ, what a...",The two work orders are for Master Plan and Si...,[3085adf8cf97d680f50d22626d8fcc40],The two specific services and their estimated ...,1,The system answer fails to provide the specifi...,Dense baseline
4,What discount is offered for a 26-week digital...,The discount is 50% off for a full 26 weeks of...,[af8704adccb9f628d70b7a89f63a3629],The discount offered for a 26-week digital sub...,5,The system answer correctly identifies the 50%...,Dense baseline
5,Why did JE request a Friday flight for a frien...,JE requested the flight because the friend had...,[ce7f6d3e024e7d99dfd480769ff800ce],JE requested a Friday flight for a friend due ...,10,The system answer accurately addresses both pa...,Dense baseline
6,Which company and city did Mark Patzelt repres...,Mark A. Patzelt from SKAPA Mining & Trading Gm...,[0e726724f1ea0872021a0487a1d27dc0],Mark Patzelt represented **SKAPA Mining&Tradin...,4,The system answer correctly identifies the com...,Dense baseline
7,What did Marcus go to the house to measure for...,Marcus went to the house to measure for curtai...,[ea5958800631884860731c2242751e16],Marcus went to the house to measure for the cu...,8,The system answer accurately and faithfully ad...,Dense baseline
8,When Epstein was indicted on felony solicitati...,Epstein was 53 and Reiter was 48. Reiter had f...,[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,* **Epstein's Age at Indictment:** When indi...,3,The system answer correctly identifies Epstein...,Dense baseline
9,"Who stated that the 98,776-acre parcel is the ...","Sheridan Gibson of Sheridan Enterprises, LLC w...",[63a7b0f798d177cc3484daeb1bc8c36c],"Sheridan Gibson stated that the 98,776 acres i...",10,The system answer conveys the same factual inf...,Dense baseline
10,What was Jeffrey Epstein's bond amount after h...,"He was released on $3,000 bond. In 1993, he pl...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,* **Bond Amount:** After his arrest for soli...,5,The system correctly provides the bond amount ...,Dense baseline
11,"Which positions did Maxwell say she hired for,...","She listed pool, gardener, chef, and/or exerci...",[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,Maxwell stated that she hired for roles such a...,2,The system answer lists incorrect positions (S...,Dense baseline
12,"What maximum width did JE set for the console,...",JE required the console to be no wider than 10...,[44aad7aa01e3091f5e5446a5c2b4d2f0],The maximum width JE wanted for the console wa...,7,The system answer correctly states the console...,Dense baseline
13,"Who sent the email on January 14, 2008, with t...","LVJET@aol.com sent the email on January 14, 20...",[25c7d6638a764d4f62a3241c913f70f6],The email was sent from **LVJET@aol.com** (Sou...,10,The System Answer accurately identifies the se...,Dense baseline
14,Which 53-year-old Manhattan money manager was ...,"Jeffrey Epstein, a 53-year-old Manhattan money...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,* **Manhattan money manager indicted on one ...,4,The system correctly identifies Jeffrey Epstei...,Dense baseline
15,Which Harvard law professor provided MySpace.c...,"Alan Dershowitz, a Harvard law professor, prov...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,The Harvard law professor who provided MySpace...,4,The system correctly identifies Alan Dershowit...,Dense baseline
16,What was the amount Epstein donated to Democra...,"He donated more than $100,000 to Democratic ca...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,* **Donation Amount and Campaigns:** Epstein...,10,The System Answer accurately reflects the Gold...,Hybrid
17,What is the date and title of the email from M...,"The email is dated Friday March 11, 2011, titl...",[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,The email from Maxwell to Jeffrey is dated Fri...,8,The System Answer accurately reflects the date...,Hybrid
18,What charges did Palm Beach police seek agains...,"On May 1, police sought warrants to arrest Eps...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,"On May 1, the department asked prosecutors to ...",9,The System Answer accurately reflects the deta...,Hybrid
19,"In the email about work orders for LSJ, what a...",The two work orders are for Master Plan and Si...,[3085adf8cf97d680f50d22626d8fcc40],The two specific services and their estimated ...,10,The System Answer accurately and faithfully re...,Hybrid
20,What discount is offered for a 26-week digital...,The discount is 50% off for a full 26 weeks of...,[af8704adccb9f628d70b7a89f63a3629],The discount offered for a 26-week digital sub...,5,The System Answer correctly identifies the 50%...,Hybrid
21,Why did JE request a Friday flight for a frien...,JE requested the flight because the friend had...,[ce7f6d3e024e7d99dfd480769ff800ce],JE requested a Friday flight for a friend due ...,8,The System Answer accurately captures the reas...,Hybrid
22,Which company and city did Mark Patzelt repres...,Mark A. Patzelt from SKAPA Mining & Trading Gm...,[0e726724f1ea0872021a0487a1d27dc0],Mark Patzelt represented **SKAPA Mining&Tradin...,10,The System Answer accurately matches the Gold ...,Hybrid
23,What did Marcus go to the house to measure for...,Marcus went to the house to measure for curtai...,[ea5958800631884860731c2242751e16],Marcus went to the house to measure for the cu...,8,The System Answer accurately reflects the Gold...,Hybrid
24,When Epstein was indicted on felony solicitati...,Epstein was 53 and Reiter was 48. Reiter had f...,[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,* **Epstein's Age:** 53 (Source document IDs...,9,The System Answer accurately matches the Gold ...,Hybrid
25,"Who stated that the 98,776-acre parcel is the ...","Sheridan Gibson of Sheridan Enterprises, LLC w...",[63a7b0f798d177cc3484daeb1bc8c36c],"The person who stated that the 98,776-acre par...",10,The System Answer accurately matches the Gold ...,Hybrid
26,What was Jeffrey Epstein's bond amount after h...,"He was released on $3,000 bond. In 1993, he pl...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,* **Bond Amount:** Epstein was released on a...,10,The System Answer accurately matches the Gold ...,Hybrid
27,"Which positions did Maxwell say she hired for,...","She listed pool, gardener, chef, and/or exerci...",[pdf:Ghislaine-Maxwell-Deposition-Only-Transcr...,Maxwell stated that her job was to find people...,4,"The System Answer lists roles (person, secreta...",Hybrid
28,"What maximum width did JE set for the console,...",JE required the console to be no wider than 10...,[44aad7aa01e3091f5e5446a5c2b4d2f0],The maximum width JE wanted for the console wa...,10,The System Answer accurately reflects all deta...,Hybrid
29,"Who sent the email on January 14, 2008, with t...","LVJET@aol.com sent the email on January 14, 20...",[25c7d6638a764d4f62a3241c913f70f6],"The email on January 14, 2008, with the subjec...",10,The System Answer correctly identifies the sen...,Hybrid
30,Which 53-year-old Manhattan money manager was ...,"Jeffrey Epstein, a 53-year-old Manhattan money...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,* **Manhattan money manager indicted:** Jeff...,10,The System Answer accurately identifies Jeffre...,Hybrid
31,Which Harvard law professor provided MySpace.c...,"Alan Dershowitz, a Harvard law professor, prov...",[pdf:Jeffrey Epstein Part 01 of 08_extracted_p...,The Harvard law professor who provided MySpace...,6,The System Answer correctly identifies Alan De...,Hybrid

### Error analysis and improvements

Compare per-question retrieval ranks and answer scores before changing models.
The current source-level recall can overstate success when one source ID belongs
to several email rows; evidence-level labels would be the next evaluation
improvement if the comparison remains ambiguous.

# **USE OF GENERATIVE AI**

In accordance with academic integrity guidelines, this section outlines the extent and nature of Generative AI assistance utilized during the design, implementation, and evaluation of this project.

###  Specific Scope of Assistance
Generative AI tools were consulted across the following technical areas:

* **Modular Architecture & Refactoring:** Assisting in decomposing the experimental pipeline into modular, decoupled Python components (`documents.py`, `rag.py`, `evaluation.py`) adhering to PEP 8 standards, complete with type annotations and comprehensive docstrings.
* **Token-Budget-Aware Chunking:** Refining the adaptive token allocation strategy in `load_or_build_chunks()`, ensuring provenance metadata headers and body text stay strictly within embedding context limits without token truncation.
* **OCR Layout Ordering & Coordinate Geometry:** Assisting in formulating the Euclidean distance-based line-to-block clustering algorithm in `_ocr_result_text()` to restore multi-column reading order from PPStructureV3 region outputs.
* **Local Quantized Inference Integration:** Troubleshooting and configuring `llama-cpp-python` GGUF execution, handling hardware-dependent CUDA/CPU fallback mechanisms, and defining turn tokens for Gemma instruction templates.
* **Automated Evaluation & LLM-as-a-Judge Framework:** Designing structured evaluation prompts, implementing provider-neutral API abstractions for OpenRouter and Google GenAI, and refining regex-based JSON extraction to reliably parse structured evaluation metrics.
* **Performance Profiling & Edge-Case Hardening:** Identifying optimization bottlenecks (such as vectorizing candidate neighbor lookups in `_add_neighbors()` for an 80x speedup) and implementing defensive input guards across retrieval functions.